<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\GoFDesignPatterns.Core\GoFDesignPatterns.Core.csproj" />
    <ProjectReference Include="..\GoFDesignPatterns.Creational\GoFDesignPatterns.Creational.csproj" />
    <ProjectReference Include="..\GoFDesignPatterns.Structural\GoFDesignPatterns.Structural.csproj" />
    <ProjectReference Include="..\GoFDesignPatterns.Behavioral\GoFDesignPatterns.Behavioral.csproj" />
    <ProjectReference Include="..\GoFDesignPatterns.ModernEnterprise\GoFDesignPatterns.ModernEnterprise.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
