<Project>
  <PropertyGroup>
    <EnableSourceControlManagerQueries>false</EnableSourceControlManagerQueries>
    <PublishRepositoryUrl>false</PublishRepositoryUrl>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <RestorePackagesPath>$(MSBuildThisFileDirectory).nuget_packages</RestorePackagesPath>
  </PropertyGroup>
</Project>
